### ISSUE TITLE
Breaks on //

### ISSUE THREAD

**Issue by ELFswe** [carlos-andres/minify-php#1]
It breaks on
`file_get_contents("php://input")`

When I try to minify the code without preserving comments, it turns into the following;
`file_get_contents("php:`
It seems to think it's a comment. Because if I tell it to preserve comments, it instead turns into the following;
`file_get_contents("php:/*input");*/`

**Comment by carlos-andres** [comment]
Oh, tyvm for report this, On my way! to prepare a fix today and push new version as soon as posible

@ELFswe this issue was addressed on version 0.3 please update and check. Let me know to close issue.

**Comment by carlos-andres** [comment]
Close this ticket,

**Comment by carlos-andres** [comment]
Close this ticket.
